name: Build Sketchware‑Pro
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu‑latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK17
        uses: actions/setup‑java@v4
        with:
          distribution: temurin
          java‑version: 17

      - name: permission
        run: chmod +x ./gradlew

      - name: compile minApi26 debug
        run: ./gradlew assembleMinApi26Debug

      - name: upload apk
        uses: actions/upload‑artifact@v4
        with:
          name: sw‑pro‑apk
          path: app/build/outputs/apk/minApi26/debug/*.apk
